//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Book()
        {
            this.tbl_Order = new HashSet<tbl_Order>();
        }
    
        public int bookId { get; set; }
        public int CategoryId { get; set; }
        public string booktitle { get; set; }
        public long ISBN { get; set; }
        public int bookYear { get; set; }
        public string bookDescription { get; set; }
        public string bookStatus { get; set; }
        public string bookImage { get; set; }
        public int bookPrice { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
    }
}
