//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int orderId { get; set; }
        public int userNo { get; set; }
        public int bookId { get; set; }
        public int orderQty { get; set; }
        public int orderAddress { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> orderEstimationDelivery { get; set; }
    
        public virtual tbl_Book tbl_Book { get; set; }
        public virtual tbl_ShippingAddress tbl_ShippingAddress { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
